# Generated by Django 6.0.6 on 2026-07-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('wallet_points', models.PositiveIntegerField(default=0)),
                ('membership_level', models.CharField(choices=[('silver', 'Silver'), ('silver_plus', 'Silver Plus'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='silver', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
