# Generated by Django 6.0.6 on 2026-07-14 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='ProductTierPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_level', models.CharField(choices=[('silver', 'Silver'), ('silver_plus', 'Silver Plus'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=20)),
                ('poinst_required', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_pricing', to='products.product')),
            ],
            options={
                'unique_together': {('product', 'membership_level')},
            },
        ),
    ]
