# Generated by Django 6.0.6 on 2026-07-15 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_short_description_producttierpricing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttierpricing',
            old_name='poinst_required',
            new_name='points_required',
        ),
    ]
