# Generated by Django 6.0.6 on 2026-07-08 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
        ('redemption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptionrecord',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.offer'),
        ),
    ]
